import { readdirSync, writeFileSync, existsSync, statSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const PKGS = 'C:/harshitJet/input-kit/packages';
const OUT = 'C:/harshitJet/input-kit/apps/site/lib';

const dirs = readdirSync(PKGS)
  .filter((d) => statSync(join(PKGS, d)).isDirectory())
  .filter((d) => existsSync(join(PKGS, d, 'test-demo', 'demo.tsx')))
  .sort();

const lines = dirs.map(
  (slug) =>
    `  '${slug}': dynamic(() => import('../../../packages/${slug}/test-demo/demo').then(pickDemo), {\n` +
    `    ssr: false,\n    loading: Loading,\n  }),`,
);

const out = `'use client';

// GENERATED by scripts/gen-demos.mjs — do not edit by hand.
// Every package's runnable demo, keyed by slug.

import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

function Loading() {
  return (
    <div className="demo-loading" role="status" aria-live="polite">
      Loading demo…
    </div>
  );
}

function NoComponent() {
  return (
    <div className="demo-loading" role="status">
      This demo file does not export a component.
    </div>
  );
}

/**
 * Demos are not consistent about what they export — most use \`Demo\`, some use
 * \`DemoApp\`, some only a default. Resolve whichever is present rather than
 * rewriting 41 files, and degrade visibly if none is.
 */
function pickDemo(mod: unknown): { default: ComponentType } {
  const candidates = mod as Record<string, unknown>;
  const found = candidates.Demo ?? candidates.DemoApp ?? candidates.default;
  return { default: typeof found === 'function' ? (found as ComponentType) : NoComponent };
}

export const demos: Record<string, ComponentType> = {
${lines.join('\n')}
};

export const demoSlugs = Object.keys(demos);
`;

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, 'demos.tsx'), out);
console.log(`demos.tsx written: ${dirs.length} demos`);
