'use client';

// GENERATED by scripts/gen-demos.mjs — do not edit by hand.
// Every package's runnable demo, keyed by slug.

import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

function Loading() {
  return (
    <div className="demo-loading" role="status" aria-live="polite">
      Loading demo…
    </div>
  );
}

function NoComponent() {
  return (
    <div className="demo-loading" role="status">
      This demo file does not export a component.
    </div>
  );
}

/**
 * Demos are not consistent about what they export — most use `Demo`, some use
 * `DemoApp`, some only a default. Resolve whichever is present rather than
 * rewriting 41 files, and degrade visibly if none is.
 */
function pickDemo(mod: unknown): { default: ComponentType } {
  const candidates = mod as Record<string, unknown>;
  const found = candidates.Demo ?? candidates.DemoApp ?? candidates.default;
  return { default: typeof found === 'function' ? (found as ComponentType) : NoComponent };
}

export const demos: Record<string, ComponentType> = {
  'card': dynamic(() => import('../../../packages/card/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'chart': dynamic(() => import('../../../packages/chart/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'clipboard': dynamic(() => import('../../../packages/clipboard/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'code': dynamic(() => import('../../../packages/code/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'color': dynamic(() => import('../../../packages/color/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'combobox': dynamic(() => import('../../../packages/combobox/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'command': dynamic(() => import('../../../packages/command/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'confetti': dynamic(() => import('../../../packages/confetti/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'crop': dynamic(() => import('../../../packages/crop/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'csv': dynamic(() => import('../../../packages/csv/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'currency': dynamic(() => import('../../../packages/currency/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'date': dynamic(() => import('../../../packages/date/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'dropzone': dynamic(() => import('../../../packages/dropzone/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'form': dynamic(() => import('../../../packages/form/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'fullscreen': dynamic(() => import('../../../packages/fullscreen/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'gauge': dynamic(() => import('../../../packages/gauge/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'hooks': dynamic(() => import('../../../packages/hooks/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'i18n': dynamic(() => import('../../../packages/i18n/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'json': dynamic(() => import('../../../packages/json/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'markdown': dynamic(() => import('../../../packages/markdown/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'mask': dynamic(() => import('../../../packages/mask/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'menu': dynamic(() => import('../../../packages/menu/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'number': dynamic(() => import('../../../packages/number/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'online': dynamic(() => import('../../../packages/online/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'otp': dynamic(() => import('../../../packages/otp/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'paste': dynamic(() => import('../../../packages/paste/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'pin': dynamic(() => import('../../../packages/pin/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'resize': dynamic(() => import('../../../packages/resize/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'search': dynamic(() => import('../../../packages/search/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'slider': dynamic(() => import('../../../packages/slider/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'sparkline': dynamic(() => import('../../../packages/sparkline/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'split': dynamic(() => import('../../../packages/split/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'table': dynamic(() => import('../../../packages/table/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'tabs': dynamic(() => import('../../../packages/tabs/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'time': dynamic(() => import('../../../packages/time/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'timeline': dynamic(() => import('../../../packages/timeline/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'toast': dynamic(() => import('../../../packages/toast/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'tooltip': dynamic(() => import('../../../packages/tooltip/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'tree': dynamic(() => import('../../../packages/tree/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'upload': dynamic(() => import('../../../packages/upload/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
  'virtual': dynamic(() => import('../../../packages/virtual/test-demo/demo').then(pickDemo), {
    ssr: false,
    loading: Loading,
  }),
};

export const demoSlugs = Object.keys(demos);
