// GENERATED by scripts/gen-registry.mjs — do not edit by hand.
// Run `npm run gen:registry` from the repo root after adding or changing a package.

export interface PackageEntry {
  slug: string;
  name: string;
  version: string;
  description: string;
  keywords: string[];
  srcLines: number;
  testLines: number;
  hasTests: boolean;
  exportNames: string[];
  hasDemo: boolean;
  isStubDemo: boolean;
  deps: string[];
}

export const packages: PackageEntry[] = [
  {
    "slug": "card",
    "name": "@input-kit/card",
    "version": "0.1.0",
    "description": "Credit card input",
    "keywords": [
      "react",
      "input-kit",
      "card",
      "typescript",
      "headless"
    ],
    "srcLines": 899,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "useCardInput",
      "CardInput",
      "ExpiryInput",
      "CvvInput",
      "detectCardType",
      "getCardInfo",
      "luhnCheck",
      "formatCardNumber",
      "formatExpiryDate",
      "validateCardNumber",
      "validateExpiryDate",
      "validateCvv",
      "maskCardNumber",
      "parseExpiryDate",
      "getMaxCardLength",
      "CARD_PATTERNS"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "chart",
    "name": "@input-kit/chart",
    "version": "0.1.0",
    "description": "Chart components",
    "keywords": [
      "react",
      "input-kit",
      "chart",
      "typescript",
      "headless"
    ],
    "srcLines": 478,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "DataPoint",
      "ChartSeries",
      "ChartProps",
      "LineChartProps",
      "BarChartProps",
      "PieChartProps",
      "LineChart",
      "BarChart",
      "PieChart",
      "useChart"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "clipboard",
    "name": "@input-kit/clipboard",
    "version": "0.1.0",
    "description": "Clipboard utilities",
    "keywords": [
      "react",
      "input-kit",
      "clipboard",
      "typescript",
      "headless"
    ],
    "srcLines": 101,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "useClipboard",
      "copyToClipboard",
      "readFromClipboard"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "code",
    "name": "@input-kit/code",
    "version": "0.1.0",
    "description": "Code block with syntax highlighting",
    "keywords": [
      "react",
      "input-kit",
      "code",
      "typescript",
      "headless"
    ],
    "srcLines": 412,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "Language",
      "Theme",
      "Token",
      "CodeBlockProps",
      "useCodeHighlight",
      "CodeBlock",
      "InlineCode",
      "THEMES"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "color",
    "name": "@input-kit/color",
    "version": "0.1.0",
    "description": "Color picker component",
    "keywords": [
      "react",
      "input-kit",
      "color",
      "typescript",
      "headless"
    ],
    "srcLines": 1449,
    "testLines": 705,
    "hasTests": true,
    "exportNames": [
      "useColorPicker",
      "ColorInput",
      "useColorInput",
      "defaultPresets",
      "hexToRgb",
      "rgbToHex",
      "rgbToHsl",
      "hslToRgb",
      "rgbToHsv",
      "hsvToRgb",
      "rgbToOklch",
      "oklchToRgb",
      "parseColor",
      "formatColor",
      "isValidColor",
      "getContrastRatio",
      "getContrastText"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "combobox",
    "name": "@input-kit/combobox",
    "version": "0.1.0",
    "description": "Autocomplete combobox",
    "keywords": [
      "react",
      "input-kit",
      "combobox",
      "typescript",
      "headless"
    ],
    "srcLines": 1139,
    "testLines": 1018,
    "hasTests": true,
    "exportNames": [
      "Combobox",
      "ComboboxOption",
      "useCombobox",
      "defaultFilterFn",
      "highlightMatch",
      "debounce",
      "getOptionValue",
      "isOptionSelected",
      "removeValueFromArray",
      "generateId",
      "createCreatableOption",
      "scrollIntoView",
      "findOptionIndexByValue"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "command",
    "name": "@input-kit/command",
    "version": "0.1.0",
    "description": "Command palette",
    "keywords": [
      "react",
      "input-kit",
      "command",
      "typescript",
      "headless"
    ],
    "srcLines": 490,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "Command",
      "CommandGroup",
      "CommandPaletteProps",
      "UseCommandPaletteOptions",
      "UseCommandPaletteReturn",
      "useCommandPalette",
      "CommandPalette",
      "CommandProvider",
      "useCommands",
      "useRegisterCommand"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "confetti",
    "name": "@input-kit/confetti",
    "version": "0.1.0",
    "description": "Confetti effects",
    "keywords": [
      "react",
      "input-kit",
      "confetti",
      "typescript",
      "headless"
    ],
    "srcLines": 165,
    "testLines": 102,
    "hasTests": true,
    "exportNames": [
      "ConfettiOptions",
      "confetti",
      "fireConfetti",
      "celebrate"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "crop",
    "name": "@input-kit/crop",
    "version": "0.1.0",
    "description": "Image cropper",
    "keywords": [
      "react",
      "input-kit",
      "crop",
      "typescript",
      "headless"
    ],
    "srcLines": 525,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "CropArea",
      "CropResult",
      "UseCropOptions",
      "UseCropReturn",
      "ImageCropperProps",
      "useCrop",
      "cropImage",
      "ImageCropper"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "csv",
    "name": "@input-kit/csv",
    "version": "0.1.0",
    "description": "CSV parser and formatter",
    "keywords": [
      "react",
      "input-kit",
      "csv",
      "typescript",
      "headless"
    ],
    "srcLines": 189,
    "testLines": 186,
    "hasTests": true,
    "exportNames": [
      "ParseOptions",
      "ParseResult",
      "parseCSV",
      "StringifyOptions",
      "stringifyCSV"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "currency",
    "name": "@input-kit/currency",
    "version": "0.1.0",
    "description": "Currency formatting",
    "keywords": [
      "react",
      "input-kit",
      "currency",
      "typescript",
      "headless"
    ],
    "srcLines": 124,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "CurrencyOptions",
      "formatCurrency",
      "formatCurrencyNumber",
      "getCurrencySymbol",
      "parseCurrency",
      "convertCurrency",
      "useCurrency"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "date",
    "name": "@input-kit/date",
    "version": "0.1.0",
    "description": "Date picker component",
    "keywords": [
      "react",
      "input-kit",
      "date",
      "typescript",
      "headless"
    ],
    "srcLines": 556,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "DatePickerProps",
      "DateRangePickerProps",
      "CalendarProps",
      "UseDatePickerOptions",
      "UseDatePickerReturn",
      "formatDate",
      "parseDate",
      "isSameDay",
      "isSameMonth",
      "isToday",
      "getDaysInMonth",
      "getFirstDayOfMonth",
      "addMonths",
      "addDays",
      "useDatePicker",
      "Calendar",
      "DatePicker"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "dropzone",
    "name": "@input-kit/dropzone",
    "version": "0.1.0",
    "description": "File dropzone",
    "keywords": [
      "react",
      "input-kit",
      "dropzone",
      "typescript",
      "headless"
    ],
    "srcLines": 555,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "FileWithPreview",
      "UseDropzoneOptions",
      "FileRejection",
      "FileError",
      "UseDropzoneReturn",
      "DropzoneProps",
      "useDropzone",
      "FilePreview",
      "Dropzone",
      "formatFileSize",
      "isValidFileType"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "form",
    "name": "@input-kit/form",
    "version": "0.1.0",
    "description": "Form validation with Zod",
    "keywords": [
      "react",
      "input-kit",
      "form",
      "typescript",
      "headless"
    ],
    "srcLines": 960,
    "testLines": 1223,
    "hasTests": true,
    "exportNames": [
      "useForm",
      "useFieldArray",
      "FormProvider",
      "useFormContext",
      "useWatch"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "fullscreen",
    "name": "@input-kit/fullscreen",
    "version": "0.1.0",
    "description": "Fullscreen API",
    "keywords": [
      "react",
      "input-kit",
      "fullscreen",
      "typescript",
      "headless"
    ],
    "srcLines": 110,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "useFullscreen"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "gauge",
    "name": "@input-kit/gauge",
    "version": "0.1.0",
    "description": "Gauge/meter",
    "keywords": [
      "react",
      "input-kit",
      "gauge",
      "typescript",
      "headless"
    ],
    "srcLines": 480,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "GaugeProps",
      "LinearGaugeProps",
      "Gauge",
      "LinearGauge",
      "SemiGauge",
      "useGaugeAnimation",
      "polarToCartesian",
      "describeArc",
      "getColorForValue"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "hooks",
    "name": "@input-kit/hooks",
    "version": "1.0.1",
    "description": "Essential React hooks collection for @input-kit",
    "keywords": [
      "react",
      "hooks",
      "typescript",
      "input-kit",
      "debounce",
      "throttle",
      "localstorage",
      "media-query",
      "intersection-observer"
    ],
    "srcLines": 1048,
    "testLines": 2559,
    "hasTests": true,
    "exportNames": [
      "useDebounce",
      "useThrottle",
      "useLocalStorage",
      "useSessionStorage",
      "useMediaQuery",
      "breakpoints",
      "useIntersectionObserver",
      "usePrevious",
      "useCountdown",
      "useNetworkStatus",
      "useClipboard",
      "useFullscreen",
      "useResizeObserver",
      "useClickOutside",
      "useKeyPress",
      "useKeyPressMultiple",
      "useScrollPosition"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "i18n",
    "name": "@input-kit/i18n",
    "version": "0.1.0",
    "description": "Internationalization",
    "keywords": [
      "react",
      "input-kit",
      "i18n",
      "typescript",
      "headless"
    ],
    "srcLines": 350,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "TranslationValue",
      "Translations",
      "LocaleMessages",
      "I18nConfig",
      "I18nContextValue",
      "TranslateFunction",
      "I18nProviderProps",
      "TransProps",
      "I18nProvider",
      "useI18n",
      "useTranslation",
      "useLocale",
      "useFormatters",
      "Trans",
      "LocaleSwitcher",
      "createTranslations",
      "mergeMessages",
      "detectBrowserLocale",
      "dateFormats",
      "numberFormats"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "json",
    "name": "@input-kit/json",
    "version": "0.1.0",
    "description": "JSON viewer",
    "keywords": [
      "react",
      "input-kit",
      "json",
      "typescript",
      "headless"
    ],
    "srcLines": 290,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "JSONViewer",
      "formatJSON",
      "isValidJSON"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "markdown",
    "name": "@input-kit/markdown",
    "version": "0.1.0",
    "description": "Markdown renderer",
    "keywords": [
      "react",
      "input-kit",
      "markdown",
      "typescript",
      "headless"
    ],
    "srcLines": 438,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "MarkdownProps",
      "MarkdownComponents",
      "useMarkdown",
      "Markdown",
      "InlineMarkdown",
      "parseMarkdown",
      "parseInline"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "mask",
    "name": "@input-kit/mask",
    "version": "0.1.0",
    "description": "Input masking",
    "keywords": [
      "react",
      "input-kit",
      "mask",
      "typescript",
      "headless"
    ],
    "srcLines": 429,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "MaskChar",
      "MaskDefinition",
      "UseMaskOptions",
      "UseMaskReturn",
      "MaskedInputProps",
      "masks",
      "useMask",
      "MaskedInput",
      "parseMask",
      "conformToMask",
      "getRawValue",
      "isComplete"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "menu",
    "name": "@input-kit/menu",
    "version": "0.1.0",
    "description": "Context menu",
    "keywords": [
      "react",
      "input-kit",
      "menu",
      "typescript",
      "headless"
    ],
    "srcLines": 487,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "MenuItem",
      "MenuPosition",
      "ContextMenuProps",
      "MenuProps",
      "UseContextMenuOptions",
      "UseContextMenuReturn",
      "useContextMenu",
      "Menu",
      "ContextMenu",
      "DropdownMenu",
      "menuSeparator",
      "menuItem"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "number",
    "name": "@input-kit/number",
    "version": "0.1.1",
    "description": "Headless number input component with locale support, currency modes, and TypeScript",
    "keywords": [
      "react",
      "number",
      "input",
      "currency",
      "locale",
      "typescript",
      "headless",
      "unstyled",
      "accessible"
    ],
    "srcLines": 634,
    "testLines": 285,
    "hasTests": true,
    "exportNames": [
      "NumberInput",
      "useNumberInput",
      "getDefaultLocale",
      "parseNumber",
      "formatNumber",
      "clamp",
      "roundToDecimals",
      "incrementValue",
      "decrementValue",
      "validateNumber"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "online",
    "name": "@input-kit/online",
    "version": "0.1.0",
    "description": "Network status",
    "keywords": [
      "react",
      "input-kit",
      "online",
      "typescript",
      "headless"
    ],
    "srcLines": 122,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "NetworkState",
      "useOnline",
      "useIsOnline"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "otp",
    "name": "@input-kit/otp",
    "version": "0.1.0",
    "description": "OTP input component",
    "keywords": [
      "react",
      "input-kit",
      "otp",
      "typescript",
      "headless"
    ],
    "srcLines": 397,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "UseOtpInputOptions",
      "UseOtpInputReturn",
      "OtpInputProps",
      "useOtpInput",
      "OtpInput",
      "OtpInputUnderline",
      "OtpInputCircle"
    ],
    "hasDemo": true,
    "isStubDemo": true,
    "deps": []
  },
  {
    "slug": "paste",
    "name": "@input-kit/paste",
    "version": "0.1.0",
    "description": "Clipboard paste handler",
    "keywords": [
      "react",
      "input-kit",
      "paste",
      "typescript",
      "headless"
    ],
    "srcLines": 453,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "PasteData",
      "UsePasteOptions",
      "UsePasteReturn",
      "PasteZoneProps",
      "usePaste",
      "usePasteZone",
      "PasteZone",
      "pasteImageToDataUrl",
      "readTextFromClipboard",
      "clipboardHasImage"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "pin",
    "name": "@input-kit/pin",
    "version": "0.1.0",
    "description": "PIN/OTP input component",
    "keywords": [
      "react",
      "input-kit",
      "pin",
      "typescript",
      "headless"
    ],
    "srcLines": 742,
    "testLines": 790,
    "hasTests": true,
    "exportNames": [
      "PinInput",
      "OtpInput",
      "usePinInput",
      "isNumeric",
      "isAlphanumeric",
      "validateChar",
      "filterValue",
      "valueToArray",
      "isCompleteValue",
      "getNextEmptyIndex",
      "getLastFilledIndex",
      "selectInputText"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "resize",
    "name": "@input-kit/resize",
    "version": "0.1.0",
    "description": "Resize observer hook",
    "keywords": [
      "react",
      "input-kit",
      "resize",
      "typescript",
      "headless"
    ],
    "srcLines": 370,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "Size",
      "ContentRect",
      "BorderBoxSize",
      "ResizeEntry",
      "UseResizeObserverOptions",
      "UseResizeObserverReturn",
      "UseElementSizeOptions",
      "UseWindowSizeOptions",
      "useResizeObserver",
      "useElementSize",
      "useWindowSize",
      "useContainerQuery",
      "useAspectRatio",
      "useOverflow",
      "useElementBounds",
      "observeElements",
      "defaultBreakpoints",
      "getBreakpoint"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "search",
    "name": "@input-kit/search",
    "version": "0.1.0",
    "description": "Search input with debounce",
    "keywords": [
      "react",
      "input-kit",
      "search",
      "typescript",
      "headless"
    ],
    "srcLines": 127,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "SearchInputProps",
      "useSearch",
      "SearchInput"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "slider",
    "name": "@input-kit/slider",
    "version": "0.1.1",
    "description": "Accessible React slider primitives with single and range thumbs",
    "keywords": [
      "react",
      "input-kit",
      "slider",
      "typescript",
      "headless"
    ],
    "srcLines": 740,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "SliderProps",
      "RangeSliderProps",
      "UseSliderOptions",
      "UseSliderReturn",
      "useSlider",
      "Slider",
      "RangeSlider"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "sparkline",
    "name": "@input-kit/sparkline",
    "version": "0.1.1",
    "description": "SVG sparkline, area, and bar charts for React dashboards",
    "keywords": [
      "react",
      "input-kit",
      "sparkline",
      "typescript",
      "headless"
    ],
    "srcLines": 643,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "SparklineProps",
      "SparkBarProps",
      "SparkAreaProps",
      "Sparkline",
      "SparkArea",
      "SparkBar",
      "InlineSparkline",
      "SparklineWithReference",
      "useSparklineData"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "split",
    "name": "@input-kit/split",
    "version": "0.1.1",
    "description": "Resizable split panes and panel layouts with keyboard support",
    "keywords": [
      "react",
      "input-kit",
      "split",
      "typescript",
      "headless"
    ],
    "srcLines": 673,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "SplitDirection",
      "SplitPaneProps",
      "PaneProps",
      "GutterProps",
      "UseSplitPaneOptions",
      "UseSplitPaneReturn",
      "useSplitPane",
      "Pane",
      "SplitPane",
      "Split",
      "CollapsibleSplit"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "table",
    "name": "@input-kit/table",
    "version": "0.1.1",
    "description": "Headless React data table with sorting, filtering, selection, and virtualization",
    "keywords": [
      "react",
      "input-kit",
      "table",
      "typescript",
      "headless"
    ],
    "srcLines": 1522,
    "testLines": 976,
    "hasTests": true,
    "exportNames": [
      "Table",
      "useTable",
      "TableHeader",
      "TableBody",
      "TablePagination",
      "sortData",
      "filterData",
      "paginateData",
      "calculatePagination",
      "defaultGetRowId",
      "clamp",
      "parseWidth",
      "debounce",
      "getCellValue"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "tabs",
    "name": "@input-kit/tabs",
    "version": "0.1.1",
    "description": "Accessible React tabs with roving focus and compound primitives",
    "keywords": [
      "react",
      "input-kit",
      "tabs",
      "typescript",
      "headless"
    ],
    "srcLines": 372,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "TabsOrientation",
      "TabsActivationMode",
      "TabsProps",
      "TabListProps",
      "TabProps",
      "TabPanelsProps",
      "TabPanelProps",
      "Tabs",
      "TabList",
      "Tab",
      "TabPanels",
      "TabPanel",
      "useTabsContext"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "time",
    "name": "@input-kit/time",
    "version": "0.1.1",
    "description": "Locale-aware relative time, countdown, and stopwatch utilities for React",
    "keywords": [
      "react",
      "input-kit",
      "time",
      "typescript",
      "headless"
    ],
    "srcLines": 737,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "TimeUnit",
      "TimeFormatOptions",
      "UseRelativeTimeOptions",
      "UseRelativeTimeReturn",
      "RelativeTimeProps",
      "TimeAgoProps",
      "TimeUntilProps",
      "parseDate",
      "getTimeDiff",
      "getTimeUnit",
      "formatRelativeTime",
      "formatDuration",
      "getSmartInterval",
      "isToday",
      "isYesterday",
      "isTomorrow",
      "formatWithContext",
      "useRelativeTime",
      "useCountdown",
      "useStopwatch",
      "RelativeTime",
      "TimeAgo",
      "TimeUntil",
      "Countdown",
      "Stopwatch"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "timeline",
    "name": "@input-kit/timeline",
    "version": "0.1.1",
    "description": "Accessible React timelines for milestones, launches, and journey storytelling",
    "keywords": [
      "react",
      "input-kit",
      "timeline",
      "typescript",
      "headless"
    ],
    "srcLines": 887,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "TimelineOrientation",
      "TimelinePosition",
      "TimelineItemStatus",
      "TimelineEvent",
      "TimelineContextValue",
      "TimelineProps",
      "TimelineItemProps",
      "TimelineMarkerProps",
      "TimelineContentProps",
      "TimelineConnectorProps",
      "UseTimelineOptions",
      "UseTimelineReturn",
      "formatTimelineDate",
      "sortEventsByDate",
      "groupEventsByDate",
      "useTimeline",
      "TimelineMarker",
      "TimelineConnector",
      "TimelineContent",
      "TimelineItem",
      "Timeline",
      "TimelineSeparator",
      "TimelineGroup"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "toast",
    "name": "@input-kit/toast",
    "version": "1.0.1",
    "description": "Headless toast notification library for React",
    "keywords": [
      "toast",
      "notification",
      "react",
      "headless",
      "typescript",
      "input-kit"
    ],
    "srcLines": 1166,
    "testLines": 632,
    "hasTests": true,
    "exportNames": [
      "ToastProvider",
      "ToastContainer",
      "Toast",
      "useToast",
      "toast",
      "configure",
      "useToastContext",
      "useToastStore",
      "POSITION_STYLES",
      "DEFAULT_DURATIONS",
      "DEFAULT_POSITION",
      "DEFAULT_MAX_TOASTS",
      "subscribe",
      "getState",
      "getActions"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "tooltip",
    "name": "@input-kit/tooltip",
    "version": "0.1.1",
    "description": "Accessible React tooltips with smart positioning and interactive content",
    "keywords": [
      "react",
      "input-kit",
      "tooltip",
      "typescript",
      "headless"
    ],
    "srcLines": 530,
    "testLines": 31,
    "hasTests": true,
    "exportNames": [
      "TooltipPlacement",
      "TooltipOptions",
      "UseTooltipReturn",
      "TooltipProps",
      "useTooltip",
      "Tooltip"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "tree",
    "name": "@input-kit/tree",
    "version": "0.1.1",
    "description": "Accessible React tree views with keyboard navigation, selection, and virtualization",
    "keywords": [
      "react",
      "input-kit",
      "tree",
      "typescript",
      "headless"
    ],
    "srcLines": 1300,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "TreeNode",
      "FlatTreeNode",
      "TreeSelectionMode",
      "TreeContextValue",
      "UseTreeOptions",
      "UseTreeReturn",
      "TreeProps",
      "TreeNodeProps",
      "flattenTree",
      "getDescendantIds",
      "getAncestorIds",
      "buildTree",
      "getVisibleNodeIds",
      "useTree",
      "TreeNodeComponent",
      "Tree",
      "VirtualTree",
      "TreeItem"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "upload",
    "name": "@input-kit/upload",
    "version": "0.1.1",
    "description": "React file upload primitives with drag-and-drop, previews, validation, and queues",
    "keywords": [
      "react",
      "input-kit",
      "upload",
      "typescript",
      "headless"
    ],
    "srcLines": 1193,
    "testLines": 0,
    "hasTests": false,
    "exportNames": [
      "UploadStatus",
      "UploadFile",
      "UploadOptions",
      "UseUploadOptions",
      "UseUploadReturn",
      "FileUploadProps",
      "UploadProgressProps",
      "UploadListProps",
      "formatFileSize",
      "getFileExtension",
      "isImageFile",
      "createPreviewUrl",
      "revokePreviewUrl",
      "parseAccept",
      "matchesAccept",
      "uploadFile",
      "useUpload",
      "UploadProgress",
      "UploadList",
      "FileUpload",
      "UploadButton"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  },
  {
    "slug": "virtual",
    "name": "@input-kit/virtual",
    "version": "0.1.1",
    "description": "React virtualization primitives for large lists and grids with dynamic sizing",
    "keywords": [
      "react",
      "input-kit",
      "virtual",
      "typescript",
      "headless"
    ],
    "srcLines": 1512,
    "testLines": 1534,
    "hasTests": true,
    "exportNames": [
      "useVirtual",
      "VirtualList",
      "VirtualGrid",
      "findItemAtOffset",
      "calculateRange",
      "buildOffsets",
      "getTotalSize",
      "throttle",
      "debounce",
      "getScrollOffset",
      "setScrollOffset",
      "calculateGridDimensions",
      "getCellPosition",
      "isNearBottom"
    ],
    "hasDemo": true,
    "isStubDemo": false,
    "deps": []
  }
];

/** @input-kit/phone lives in its own repository, so it is listed but not demoed here. */
export const externalPackages = [
  {
    slug: 'phone',
    name: '@input-kit/phone',
    version: '0.3.0',
    description:
      'Headless React phone input with 245 calling regions, libphonenumber-powered formatting and validation',
    repo: 'https://github.com/harshit-d3v/input-kit-phone',
  },
];

export const bySlug = new Map(packages.map((p) => [p.slug, p]));

export const totals = {
  count: 41,
  srcLines: 25794,
  testLines: 10041,
  tested: 12,
};
